use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.004003
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;

add_stopwords(<DATA>);
all_pod_files_spelling_ok(qw( bin lib  ));
__DATA__
shantanu
bhadoria
CBusDevicePath
CDeviceAddress
Datasheet
dev
libi
smbus
xs
readByteData
writeByteData
processCall
readByte
readWordData
writeByte
writeQuick
writeWordData
readNBytes
Destructor
fileError
Shantanu
Bhadoria
at
cpan
dott
org
lib
Device
SMBus
